[muxtools]
show_name = "Nice Series"
clean_work_dirs = false
out_dir = "premux"
out_name = "$show$ - $ep$ (premux)"
mkv_title_naming = "$show$ - $ep$"
debug = true
error_on_danger = false

arbitrary_value = "woah"

# Pinned versions are used for the tests, both in CI and locally
[muxtools.binaries]
prefer = "local"
packages = ["mkvtoolnix==101.0", "opus-tools==0.2-libopus-1.6.1", "flac==1.5.0.post1", "ffmpeg==9.0.1-27-g9b0578816c-2026-09-07", "sox-ng==14.8.1"]
