name: Lint
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.12', '3.14']

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive
      - name: Setup uv
        uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0

      - name: Run ruff check (Python ${{ matrix.python-version }})
        run: uv run --python ${{ matrix.python-version }} ruff check ./muxtools/

      - name: Run mypy (Python ${{ matrix.python-version }})
        run: uv run --python ${{ matrix.python-version }} mypy ./muxtools/

      - name: Post webhook for failure
        if: failure() && github.event_name != 'pull_request'
        uses: Jaded-Encoding-Thaumaturgy/discord-failure-notifier@v1
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
